resources:
  containers:
  - container: rust_image
    image: rust:1.30.1
jobs:
- job: hello_cargo
  displayName: Build Hello Cargo
  pool: 
    vmImage: ubuntu-16.04
  container: rust_image
  steps:
  - bash: cargo build
    workingDirectory: hello_cargo